# Generated by Django 4.0.5 on 2022-06-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_remove_audio_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='text',
            field=models.FileField(default=1, upload_to='text/'),
            preserve_default=False,
        ),
    ]
