# Generated by Django 4.0.5 on 2022-06-08 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_audio_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='text',
        ),
    ]
