# Generated by Django 4.0.5 on 2022-06-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_remove_audio_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
